# Generated by Django 5.1.7 on 2025-03-10 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0002_secret"),
    ]

    operations = [
        migrations.RenameField(model_name="secret", old_name="title", new_name="name",),
    ]
